name: todark
description: A new Flutter project.

publish_to: 'none'

version: 1.2.8+18

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  isar: ^3.0.5
  intl: ^0.17.0
  swipe: ^0.0.1
  iconsax: ^0.0.8
  path_provider: ^2.0.11
  table_calendar: ^3.0.8
  flutter_typeahead: ^4.1.1
  isar_flutter_libs: ^3.0.5
  flex_color_picker: ^3.0.2
  flutter_easyloading: ^3.0.5
  custom_navigation_bar: ^0.8.2
  sleek_circular_slider: ^2.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  image_path: "assets/icons/icons_todo.png"
  adaptive_icon_background: "#1F1F1F"
  adaptive_icon_foreground: "assets/icons/icons_todo2.png"

flutter_native_splash:
  color: "#1F1F1F"
  image: "assets/icons/icons.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
