name: dark_todo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  equatable: ^2.0.3
  flutter_easyloading: ^3.0.5
  dotted_border: ^2.0.0+2
  step_progress_indicator: ^1.0.2
  intl: ^0.17.0
  flutter_screenutil: ^5.5.3+2
  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.15
  animated_theme_switcher: ^2.0.6
  flutter_local_notifications: ^9.8.0+1
  flutter_native_timezone: ^2.0.0
  timeline_tile: ^2.0.0
  horizontal_center_date_picker: ^2.1.1
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.7

flutter_icons:
  android: true
  image_path: "assets/images/icons_todo.png"
  adaptive_icon_background: "#1F1F1F"
  adaptive_icon_foreground: "assets/images/icons_todo.png"

flutter_native_splash:
  color: "#1F1F1F"
  image: "assets/images/icons.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
