name: todark
description: A new Flutter project.

publish_to: 'none'

version: 1.2.0+10

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  isar: ^3.0.2
  intl: ^0.17.0
  iconsax: ^0.0.8
  path_provider: ^2.0.11
  table_calendar: ^3.0.8
  isar_flutter_libs: ^3.0.2
  flex_color_picker: ^2.6.1
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.5.3+2
  custom_navigation_bar: ^0.8.2
  sleek_circular_slider: ^2.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_native_timezone: ^2.0.0
  lazy_load_indexed_stack: ^0.1.4
  flutter_local_notifications: ^9.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.7
  isar_generator: ^3.0.2
  build_runner: ^2.0.0

flutter_icons:
  android: true
  image_path: "assets/icons/icons_todo.png"
  adaptive_icon_background: "#1F1F1F"
  adaptive_icon_foreground: "assets/icons/icons_todo2.png"

flutter_native_splash:
  color: "#1F1F1F"
  image: "assets/icons/icons.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
